import io
import os
import re
import uuid
from pathlib import Path
from typing import Tuple, Optional, List
import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

def set_cell_background(cell, hex_color: str):
    """Sets background shading of a docx table cell."""
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'), 'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'), hex_color.replace('#', ''))
    tc_pr.append(shd)

def set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    """Sets internal cell margins in twips (1 pt = 20 twips)."""
    tc_pr = cell._tc.get_or_add_tcPr()
    tc_mar = OxmlElement('w:tcMar')
    for margin_name, val in [('w:top', top), ('w:bottom', bottom), ('w:left', left), ('w:right', right)]:
        node = OxmlElement(margin_name)
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tc_mar.append(node)
    tc_pr.append(tc_mar)

def add_styled_paragraph(doc, text: str, style_name: str = 'Normal', space_after: int = 4, is_bold: bool = False):
    p = doc.add_paragraph(style=style_name)
    p.paragraph_format.space_after = Pt(space_after)
    p.paragraph_format.line_spacing = 1.15
    
    # Parse bold / italics inside text
    # Clean up markdown formatting into runs
    parts = re.split(r'(\*\*.*?\*\*|\*.*?\*|`.*?`)', text)
    for part in parts:
        if not part:
            continue
        if part.startswith('**') and part.endswith('**'):
            run = p.add_run(part[2:-2])
            run.bold = True
        elif part.startswith('*') and part.endswith('*'):
            run = p.add_run(part[1:-1])
            run.italic = True
        elif part.startswith('`') and part.endswith('`'):
            run = p.add_run(part[1:-1])
            run.font.name = 'Consolas'
            run.font.size = Pt(9.5)
            run.font.color.rgb = RGBColor(15, 23, 42)
        else:
            run = p.add_run(part)
            if is_bold:
                run.bold = True
    return p

def markdown_to_docx(
    markdown_content: str,
    title: str = "OmniTask Document Deliverable",
    output_filename: Optional[str] = None,
    output_dir: Optional[Path] = None,
) -> Tuple[str, Path]:
    """
    Compiles markdown content into a publication-grade Microsoft Word (.docx) document.
    Returns (docx_url, physical_path).
    """
    if not output_dir:
        output_dir = Path(__file__).resolve().parent.parent.parent / "uploads" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    if not output_filename:
        safe_base = re.sub(r"[^a-zA-Z0-9_-]", "_", title.lower()).strip("_")[:40] or "document"
        unique_suffix = uuid.uuid4().hex[:8]
        output_filename = f"{safe_base}_{unique_suffix}.docx"

    if not output_filename.endswith(".docx"):
        output_filename += ".docx"

    file_path = output_dir / output_filename

    doc = docx.Document()

    # Set page margins (1 inch all around)
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
        
        # Header
        header = section.header
        hp = header.paragraphs[0]
        hp.text = "OmniTask AI • Verified Document Deliverable"
        hp.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        if hp.runs:
            hp.runs[0].font.size = Pt(8.5)
            hp.runs[0].font.color.rgb = RGBColor(100, 116, 139)

        # Footer
        footer = section.footer
        fp = footer.paragraphs[0]
        fp.text = "Prepared by OmniTask AI Multi-Agent Swarm • Confidential"
        fp.alignment = WD_ALIGN_PARAGRAPH.LEFT
        if fp.runs:
            fp.runs[0].font.size = Pt(8.5)
            fp.runs[0].font.color.rgb = RGBColor(148, 163, 184)

    # Document Title Banner
    title_p = doc.add_paragraph()
    title_p.paragraph_format.space_before = Pt(0)
    title_p.paragraph_format.space_after = Pt(2)
    t_run = title_p.add_run(title)
    t_run.font.name = 'Calibri'
    t_run.font.size = Pt(22)
    t_run.bold = True
    t_run.font.color.rgb = RGBColor(30, 58, 138)  # Deep Navy

    sub_p = doc.add_paragraph()
    sub_p.paragraph_format.space_after = Pt(14)
    s_run = sub_p.add_run("Official Deliverable • Generated by OmniTask Multi-Agent Engine")
    s_run.font.name = 'Calibri'
    s_run.font.size = Pt(10)
    s_run.font.color.rgb = RGBColor(100, 116, 139)

    # Process markdown lines
    lines = markdown_content.split('\n')
    in_code_block = False
    code_lines = []
    code_block_lang = ""

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Code block fence
        if stripped.startswith("```"):
            if in_code_block:
                in_code_block = False
                is_md_block = code_block_lang in ["markdown", "md"] or any(l.strip().startswith(("#", "##", "- ", "* ", "1.")) for l in code_lines[:6])
                if is_md_block:
                    # Unpack markdown lines into the main stream to be rendered as styled headings and text
                    lines = lines[:i] + code_lines + lines[i+1:]
                    code_lines = []
                    continue

                if code_lines:
                    # Render code block in a shaded 1-cell table
                    tbl = doc.add_table(rows=1, cols=1)
                    tbl.alignment = WD_TABLE_ALIGNMENT.CENTER
                    cell = tbl.cell(0, 0)
                    cell.width = Inches(6.5)
                    set_cell_background(cell, "F8FAFC")
                    set_cell_margins(cell, top=120, bottom=120, left=180, right=180)
                    
                    cp = cell.paragraphs[0]
                    cp.paragraph_format.space_after = Pt(0)
                    c_run = cp.add_run("\n".join(code_lines))
                    c_run.font.name = 'Consolas'
                    c_run.font.size = Pt(9.0)
                    c_run.font.color.rgb = RGBColor(15, 23, 42)
                    
                    p_spacer = doc.add_paragraph()
                    p_spacer.paragraph_format.space_after = Pt(4)
                code_lines = []
            else:
                code_block_lang = stripped[3:].strip().lower()
                in_code_block = True
                code_lines = []
            i += 1
            continue

        if in_code_block:
            code_lines.append(line)
            i += 1
            continue

        if not stripped:
            i += 1
            continue

        # Horizontal Rule
        if stripped in ["---", "***", "___"]:
            hr_p = doc.add_paragraph()
            hr_p.paragraph_format.space_after = Pt(6)
            hr_run = hr_p.add_run("―" * 45)
            hr_run.font.color.rgb = RGBColor(226, 232, 240)
            i += 1
            continue

        # Markdown Headings: H1 (#), H2 (##), H3 (###), H4 (####), H5 (#####)
        h_match = re.match(r'^(#{1,6})\s+(.*)$', stripped)
        if h_match:
            level = len(h_match.group(1))
            heading_text = h_match.group(2).strip()
            
            # Clean any internal formatting hashes or quotes
            heading_text = re.sub(r'[*_`]', '', heading_text)

            hp = doc.add_paragraph()
            hp.paragraph_format.keep_with_next = True
            
            if level == 1:
                hp.paragraph_format.space_before = Pt(14)
                hp.paragraph_format.space_after = Pt(6)
                hrun = hp.add_run(heading_text)
                hrun.font.name = 'Calibri'
                hrun.font.size = Pt(16)
                hrun.bold = True
                hrun.font.color.rgb = RGBColor(30, 41, 59)
            elif level == 2:
                hp.paragraph_format.space_before = Pt(12)
                hp.paragraph_format.space_after = Pt(5)
                hrun = hp.add_run(heading_text)
                hrun.font.name = 'Calibri'
                hrun.font.size = Pt(13.5)
                hrun.bold = True
                hrun.font.color.rgb = RGBColor(51, 65, 85)
            elif level == 3:
                hp.paragraph_format.space_before = Pt(10)
                hp.paragraph_format.space_after = Pt(4)
                hrun = hp.add_run(heading_text)
                hrun.font.name = 'Calibri'
                hrun.font.size = Pt(11.5)
                hrun.bold = True
                hrun.font.color.rgb = RGBColor(71, 85, 105)
            else:  # H4, H5, H6 (e.g. "Question 1: Multiple Choice")
                hp.paragraph_format.space_before = Pt(8)
                hp.paragraph_format.space_after = Pt(3)
                hrun = hp.add_run(heading_text)
                hrun.font.name = 'Calibri'
                hrun.font.size = Pt(10.5)
                hrun.bold = True
                hrun.font.color.rgb = RGBColor(15, 23, 42)
            i += 1
            continue

        # Bullet lists (- , * , + )
        if stripped.startswith(("- ", "* ", "+ ")):
            bullet_text = stripped[2:].strip()
            bp = doc.add_paragraph(style='List Bullet')
            bp.paragraph_format.space_after = Pt(3)
            bp.paragraph_format.line_spacing = 1.15
            # Add runs
            parts = re.split(r'(\*\*.*?\*\*|\*.*?\*|`.*?`)', bullet_text)
            for part in parts:
                if not part:
                    continue
                if part.startswith('**') and part.endswith('**'):
                    r = bp.add_run(part[2:-2])
                    r.bold = True
                elif part.startswith('*') and part.endswith('*'):
                    r = bp.add_run(part[1:-1])
                    r.italic = True
                elif part.startswith('`') and part.endswith('`'):
                    r = bp.add_run(part[1:-1])
                    r.font.name = 'Consolas'
                else:
                    bp.add_run(part)
            i += 1
            continue

        # Numbered lists (1. , 2) , A) , B) )
        list_match = re.match(r'^([0-9]+[\.\)]|[A-Z][\.\)])\s+(.*)$', stripped)
        if list_match:
            prefix = list_match.group(1)
            item_text = list_match.group(2).strip()
            lp = doc.add_paragraph()
            lp.paragraph_format.left_indent = Inches(0.25)
            lp.paragraph_format.space_after = Pt(3)
            lp.paragraph_format.line_spacing = 1.15
            p_run = lp.add_run(f"{prefix} ")
            p_run.bold = True
            
            parts = re.split(r'(\*\*.*?\*\*|\*.*?\*|`.*?`)', item_text)
            for part in parts:
                if not part:
                    continue
                if part.startswith('**') and part.endswith('**'):
                    r = lp.add_run(part[2:-2])
                    r.bold = True
                elif part.startswith('*') and part.endswith('*'):
                    r = lp.add_run(part[1:-1])
                    r.italic = True
                elif part.startswith('`') and part.endswith('`'):
                    r = lp.add_run(part[1:-1])
                    r.font.name = 'Consolas'
                else:
                    lp.add_run(part)
            i += 1
            continue

        # Standard Body Paragraph
        add_styled_paragraph(doc, stripped, space_after=4)
        i += 1

    doc.save(str(file_path))
    docx_url = f"/api/generated-media/{file_path.name}"
    return docx_url, file_path
